### PR TITLE
Consumption Saving Refactor - move examples to notebooks - tests boilerplate

### PR DESCRIPTION
**Pull request by MridulS**
I have removed the def main() code from ConsIndShockModel.py file and moved it to a example file.
This file will be present in the examples/ directory and parts of that file will be in the tests/ directory to create base level testing coverage of the module.

We also need to discuss what is exposed to the final user, for example `ValueFunc`, `MargValueFunc` and `MargMargValueFunc` are use by other classes to solve the model but I don't see users using this directly. Should this be exposed in the final documentation on readthedocs?

In this PR I'll repeat the same with all the other models and files in the ConsumptionSaving folder.

In this refactor I am also removing py2 specific dependencies in the ConsumptionSaving module as the py2 drop date is 15th Jan according to the roadmap.

### CODE REVIEW

**Comment by MridulS** [comment]
related: https://github.com/econ-ark/HARK/issues/370
https://github.com/econ-ark/HARK/issues/440

**Comment by MridulS** [comment]
[Build fails because it is running for py2.7 too]

**Comment by MridulS** [comment]
Move def main to example_model.py

- [x] ConsAggShockModel.py
- [x] ConsPortfolioModel.py 
- [x] ConsGenIncProcessModel.py
- [x] ConsPrefShockModel.py
- [x] ConsIndShockModel.py
- [x] ConsRepAgentModel.py
- [x] ConsMarkovModel.py
- [x] ConsMedModel.py
- [x] TractableBufferStockModel.py

**Comment by sbenthall** [comment]
Would you like me to review this some time?

**Comment by MridulS** [comment]
@sbenthall that would be great! Almost done with this one.

**Comment by MridulS** [comment]
@sbenthall Can you go through this once, I don't want to make more changes to this as it will create a big PR. I'll start a new PR with further changes.

**Comment by sbenthall** [comment]
@MridulS Sorry for the slow action on this one.
I merged updates from master.
It looks like there are some tests failing.

**Comment by MridulS** [comment]
Ah the consumption parameters change is failing the tests, I'll update this PR.

**Comment by MridulS** [comment]
okay this is weirder than I thought, something is breaking between import structure of python3.6 and python3.7

This works for py3.7 and py3.8

**Comment by sbenthall** [comment]
Because the 3.6 build was broken on an issue involving import of the `ConsumptionSaving` files, and because there was a merge conflict with `master` over `HARK/__init__.py`, I took the liberty of trying to resolve the merge.

I removed this line:
`from HARK.ConsumptionSaving import *`

which seemed to be opening up a new way to import ConsumptionSaving files.
If I understand correctly, that line lets you do:
`from HARK import MarkovConsumerType`

instead of
`from HARK.ConsumptionSaving import MarkovConsumerType`

I see now that you used the former style (`from HARK import MarkovConsumerType`) elsewhere in the PR.
So I have to apologize for breaking something new.

A change I would test myself if I could use the different build environments in GitHub actions myself is whether if all these references are changed back to `from HARK.ConsumptionSaving import XXXXXX`, does that then pass the 3.6 build test.

**Comment by MridulS** [comment]
reverted changes to make this py2.7 compatible and make it v0.10.4 friendly

**Pull request merged**
