### PR TITLE
Adding Transition Matrix Methods [WIP]

### PR DESCRIPTION
**Pull request by wdu9**
Once a model is solved, there are two ways of determining the behavior of a population that behaves according to that model: Monte Carlo simulation, and Markov transition matrix iteration.  Until now, the only method available in HARK has been Monte Carlo.  This PR implements a transition matrix version.

Please ensure your pull request adheres to the following guidelines:

- [x] Tests for new functionality/models or Tests to reproduce the bug-fix in code.
- [x] Updated documentation of features that add new functionality.
- [x] Update CHANGELOG.md with major/minor changes.

### CODE REVIEW

**Review by llorracc — COMMENTED** [review]
@wdu9,

Now that Mateo and I have a DemARK notebook explaining Harmenberg, I'd like you to cross reference between the code and that notebook.  That is, here you should have a comment directing someone reading the code to look at the Harmenberg-Aggregation DemARK notebook for a detailed description, and if there are any changes that would be appropriate in the Harmenberg-Aggregation DemARK notebook, please make those as well (maybe there are none needed there).

**Comment by wdu9** [comment]
In the Jupyter Notebook, consider whether the dictionary is necessary, or at least, consider whether only a few items are modified.

**Comment by wdu9** [comment]
When referencing Mateo and Chris' notebook, don't use github URL, use https://econ-ark.org/materials/harmenberg-aggregation?launch

**Comment by wdu9** [comment]
Explain why the steady state is computed at the beginning of the MIT shock experiment. Explain why I'm computing the steady state.

**Comment by wdu9** [comment]
Reword last cell, don't call it original method.

**Pull request closed without merging**
