### PR TITLE
N-dimensional 'jump_to_grid'

### PR DESCRIPTION
**Pull request by Mv77**
The transition-matrix way of doing things involves spreading the mass of simulated points to an exogenous grid of the state space. We currently can do this for 1D and 2D state spaces with the `jump_to_grid_1D` and `jump_to_grid_2D` methods. This PR adds a method called `mass_to_grid`, which achieves the same goal, but for ND state spaces.

It adds tests that verify that the output of the new function is the same as that of `jump_to_grid_1D` and `jump_to_grid_2D` . In my own tests, `mass_to_grid` is about ~2 times slower than the `jump_to_grid_1D` and `jump_to_grid_2D` methods. Still, I thought it would be good to have the general version around at least for testing higher-dimensional models. If performance ever becomes an issue we can try to make it faster, or code up `jump_to_grid_3D`. But as far as I understand, this part of the matrix-method algorithms is a tiny fraction of their total time so it does not look like the ~2 factor is a concern.

Please ensure your pull request adheres to the following guidelines:

- [ ] Tests for new functionality/models or Tests to reproduce the bug-fix in code.
- [ ] Updated documentation of features that add new functionality.
- [ ] Update CHANGELOG.md with major/minor changes.

### CODE REVIEW

**Comment by llorracc** [comment]
Looks awesome!  Let's discuss tomorrow.

**Comment by Mv77** [comment]
Codecov is reporting a lot of misses...but I think the tests are pretty exhaustive and I believe it might be because of numba?
@alanlujan91 have you run into this before?

**Comment by alanlujan91** [comment]
We updated codecov to the new version and it seems it is now much more exhaustive... @MridulS might be able to help

**Comment by sbenthall** [comment]
https://stackoverflow.com/questions/26875191/analyzing-coverage-of-numba-wrapped-functions

**Comment by sbenthall** [comment]
"define the NUMBA_DISABLE_JIT environment variable when you run your coverage measurement. "

https://github.com/econ-ark/HARK/blob/master/.github/workflows/coverage.yml

**Comment by sbenthall** [comment]
https://github.com/keurfonluu/fteikpy/blob/master/.github/workflows/ci.yml#L29

**Comment by Mv77** [comment]
The empty commit
Suggested by our friend @MridulS 
Has failed,
And now also empty
Is my soul.

@sbenthall @alanlujan91

**Comment by Mv77** [comment]
I am not sure how that could be, but I can certainly test using the same environment flag when I get back home.

**Comment by Mv77** [comment]
@alanlujan91 nope, still failing coverage

**Comment by alanlujan91** [comment]
it builds on every system/python and runs all the examples, I think we should merge this and try to figure out codecov config later

**Review by alanlujan91 — APPROVED** [review]

**Pull request merged**
