### PR TITLE
[WIP] estimation using `estimagic`

### PR DESCRIPTION
**Pull request by alanlujan91**
Please ensure your pull request adheres to the following guidelines:

- [ ] Tests for new functionality/models or Tests to reproduce the bug-fix in code.
- [ ] Updated documentation of features that add new functionality.
- [ ] Update CHANGELOG.md with major/minor changes.

### CODE REVIEW

**Comment by alanlujan91** [comment]
currently failing because example notebook requires additional plotting libraries

**Comment by dedwar65** [comment]
I've tried running the SMM notebook thats created in this PR. Apparently, estimagic has been renamed to optimagic. So far, this only amounts to importing estimagic and optimagic at the start of the code.

However, the notebook takes over 34 minutes to run the final `estimate_msm` command. Surely it didn't take this long before. Makes me wonder if this is related to the project change from optimagic to estimagic. I will keep trying to debug myself

**Comment by mnwhite** [comment]
Is this WIP or should be reviewed?

**Comment by alanlujan91** [comment]
should be reviewed

**Pull request merged**
