### PR TITLE
Journey 1; targeting PhD students - new version to compile all notebooks. 

### PR DESCRIPTION
**Pull request by janrosa1**
Additionally, I changed a notebook on the individual consumers, to make it more consistent with quick start  (only a version in the documentation directory)

### CODE REVIEW

**Comment by sbenthall** [comment]
@janrosa1 this is great work!

I've had the make a few edits as part of the merge.
You should be able to get them into this PR #380 by merging my changes into your `master` branch:
https://github.com/janrosa1/HARK/pull/4

**Comment by janrosa1** [comment]
Thanks, will check it! Sorry, for late answer.

czw., 6 lut 2020 o 11:44 Sebastian Benthall <notifications@github.com>
napisał(a):

**Comment by sbenthall** [comment]
@janrosa1 Would you permit me to make the changes necessary to complete this merge myself?

**Comment by sbenthall** [comment]
@llorracc Can you please check with @janrosa1 about this?

**Comment by janrosa1** [comment]
I am still new to big group project at Github, thought that I do need to
authorize your pull request, as you are a contributor to the main project.
I am very sorry about this, I hope you did not lose too much time.
Best,
Jan

czw., 5 mar 2020, 09:08 użytkownik Sebastian Benthall <
notifications@github.com> napisał:

**Comment by janrosa1** [comment]
I submitted a review, please let me know if it is what I was supposed to
do.
Again, I am very sorry for this.
Best,Jan

czw., 5 mar 2020 o 09:38 Jan Rosa <jan.rosa1993@gmail.com> napisał(a):

**Comment by sbenthall** [comment]
OK, no problem @janrosa1 . Just wanted to respect your contributions :) Thank you for your good work!

**Comment by janrosa1** [comment]
Thank you! I looked at the changes before (the not technical ones) and do
not have any comments, but should let you know about it.

czw., 5 mar 2020 o 09:50 Sebastian Benthall <notifications@github.com>
napisał(a):

**Pull request merged**
