### PR TITLE
Make HARK substantially compatible with both Py2 and Py3

### PR DESCRIPTION
**Pull request by npalmer-professional**
This pull request is a first step in making HARK substantially compatible with both Python 2 and Python 3. See [commit notes here](https://github.com/npalmer-professional/HARK-1/commit/05e22da3bfa80908b0f399c4962fec98f702da9a) for more details.

**Note** that this pull request may be substantially superseded by another PR on the same topic, particularly if the items in the above commit message are addressed.

### CODE REVIEW

**Comment by npalmer-professional** [comment]
Quick note: there is a place in that commit message that says "2.6" where it should say "3.6" I'll fix it as soon as I can figure out how to edit commit messages...

**Comment by mnwhite** [comment]
Merge of "Installibility" PR made this PR full of conflicts; all the files are now in different places.  Should we close this PR / branch and recreate the work for the new package-ified HARK?

**Comment by npalmer-professional** [comment]
Yes, I think that is the cleanest approach.

**Comment by npalmer-professional** [comment]
@mnwhite Yes, I think that is the cleanest approach. I am closing this PR now, and will send a new pull request likely sometime tomorrow.

**Pull request closed without merging**
