### PR TITLE
C and c with Sticky Expectations

### PR DESCRIPTION
**Pull request by mnwhite**
Test PR, adding an embryonic model and application.

Also adds a missing line to AggShockModel in SmallOpenEconomy and fixes a type-checking error in HARKsimulation.

### CODE REVIEW

**Comment by mnwhite** [comment]
For some reason this PR includes everything that Edmund did.  Is that because I screwed around with the repo too much and had to rebase and/or reset?

**Comment by mnwhite** [comment]
Also, nearly all of these are junk commits that we really *don't* want to appear in the master commit history.

**Comment by mnwhite** [comment]
Perfect, that commit appears on my remote branch.  Squash and merge in this case?

**Comment by dclow** [comment]
Test of pull request protocol

**Pull request merged**
