### PR TITLE
HARK 2.0 pre-alpha/code for BST notebook and dashboard

### PR DESCRIPTION
**Pull request by llorracc**
This code has been tested with the draft notebook for the BST REMARK 

which is at https://github.com/llorracc/BufferStockTheory

It is intended as a sketch of ideas for HARK 2.0 rather than as something ready to be merged into the existing HARK 1.0 master anytime soon.

### CODE REVIEW

**Comment by sbenthall** [comment]
You have requested a review.
This PR has 171 commits and touches 106 files. It currently has several merge conflicts.
Many of the files that are touched a .spyproject files which should not be committed to the master branch.

It would be easier to review a cleaner PR.

Barring that, it would be helpful if you could name the files which have substantive changes that you would like to have reviewed.

**Comment by llorracc** [comment]
Seb,

Virtually all of the 106 files are things that were automatically changed by my local build of the sphinx documentation.  

As I said when we discussed the prior PR, that one contained all of the substantive changes outside of core.py and ConsIndShockModel.py.  Everything else is either very minor, or meaningless, like the sphinx rebuild.  

Since so much has changed, my sense was that trying to look at each of 171 PRs was not going to be an efficient way to evaluate the new code.  That's why I emphasized that I'd like to start evaluating it by running the BST notebook and dashboard.

**Comment by llorracc** [comment]
@sbenthall @MridulS 

I did a bit of research and I guess what I should really have done for this was a "draft PR" as described in a 2019 post on the GitHub blog, which explicitly does NOT request a merge into master and is for the kind of review I want from you and Mridul and Matt.  Have done a little bit of further cleanup and posted a "draft commit" as "Update-0p11-for-QE-revised"

PS.  The meaningless changes that weren't sphinx junk were the results of running unit tests locally.  So, again, all the focus should be on ConsIndShockModel and the derivative new files that it pulls in, plus core.py.

**Comment by MridulS** [comment]
closing this one, continued in https://github.com/econ-ark/HARK/pull/1055

**Pull request closed without merging**
