### PR TITLE
Update RNG

### PR DESCRIPTION
**Pull request by alanlujan91**
Since Numpy version 1.17.0 scipy introduced Generator as a replacement to RandomState. 

This PR updates HARK to use Generator as recommended in https://numpy.org/doc/stable/reference/random/index.html#quick-start

- [x] Tests for new functionality/models or Tests to reproduce the bug-fix in code.
- [x] Updated documentation of features that add new functionality.
- [x] Update CHANGELOG.md with major/minor changes.

### CODE REVIEW

**Comment by llorracc** [comment]
Are these the kinds of errors that would disappear if we scaled back our degree of precision?  If so, that's the solution.

**Comment by alanlujan91** [comment]
# TODO: level of precision to 3 or 4 decimals

**Comment by alanlujan91** [comment]
assertAlmostEqual\((.*), (\d*\.\d{5})\)

**Comment by llorracc** [comment]
@alanlujan91 let's discuss merging this in tomorrow's meeting.

**Pull request merged**
