### PR TITLE
Dictionary and resolving error message

### PR DESCRIPTION
**Pull request by dedwar65**
Commits from 1/16 included:
- creating a dictionary for the "ConsPortfolioType" 
- resolving the "TypeError" in the final code block, which renders an error message on the documentation site.

### CODE REVIEW

**Comment by sbenthall** [comment]
The failing test on this PR seems to be about `Rfree` being a list instead of a float.
Is this connected to this error? https://github.com/sbenthall/SHARKFin/issues/186#issuecomment-1410520453 ping @alanlujan91
See #1106 #1132 I think the root problem relates to #664

**Comment by alanlujan91** [comment]
@dedwar65 is this done?

**Comment by dedwar65** [comment]
This one is also done, so long as your fix to the time-varying interest rate goes along with it.

From: alanlujan91 ***@***.***>
Date: Sunday, February 5, 2023 at 8:20 PM
To: econ-ark/HARK ***@***.***>
Cc: Decory Edwards ***@***.***>, Mention ***@***.***>
Subject: Re: [econ-ark/HARK] Dictionary and resolving error message (PR #1219)

      External Email - Use Caution





@dedwar65<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdedwar65&data=05%7C01%7Cdedwar65%40jhu.edu%7C52c2aac8763c4edebce308db07e047f7%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638112432086103364%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7OQHeVgijdWqOEx40Egz%2FtuGml%2Fzyr%2BPo14cQXXqT2o%3D&reserved=0> is this done?

**Comment by alanlujan91** [comment]
Merging these improvements to notebooks before #1221, will fix conflicts there.

**Pull request merged**
