### PR TITLE
clock is removed in py3.8

### PR DESCRIPTION
**Pull request by MridulS**

### CODE REVIEW

**Comment by MridulS** [comment]
travis fails for py2.7 as perf_counter is py3 only.

**Comment by mnwhite** [comment]
We can use time.time() or process_time(), right?

We can also drop the py27 Travis tests next week. But we really ought to
announce this.

**Comment by MridulS** [comment]
True. Dropping py2.7 is on the timeline wiki for 15/01/2020 but we should
make a more public announcement.

**Comment by MridulS** [comment]
https://github.com/econ-ark/HARK/pull/471

**Pull request closed without merging**
