### PR TITLE
Update docstring of simDeath() in core.

### PR DESCRIPTION
**Pull request by pkofod**
Docstring doesn't match behavior.

### CODE REVIEW

**Comment by mnwhite** [comment]
Good catch! But my typo is in the opposite direction: the docstring says what it's *supposed* to do, but the np.ones is supposed to be an np.zeros.  We can also consider removing that print statement and letting "no death and replacement" be the default.

**Comment by pkofod** [comment]
> But my typo is in the opposite direction: the docstring says what it's _supposed_ to do, but the np.ones is supposed to be an np.zeros.

I thought that might be the case, but I couldn't determine if you intended for everyone to die by default and thereby force people to respect the printed message, or if it was a typo the other way. In that case, I will change the behavior! (and add a test), and remove the printed message. Then noone dies, unless the users specifies it.

**Comment by llorracc** [comment]
Sounds like "what to do" is now agreed on this?  Or is more discussion needed?

**Comment by mnwhite** [comment]
I think Patrick already did it.  Let me take a look tonight and see if it's
ready to merge (probably is).

**Comment by pkofod** [comment]
I removed the warning, and changed the default.

**Comment by shaunagm** [comment]
@pkofod, can you write a release note for this?

**Comment by pkofod** [comment]
"Fix unintended behavior in default simDeath(). Previously, all agents would die off in the first period, but they were meant to always survive."

This change is technically breaking. Before, there would be a warning that the users should define their own method and all agents would die. Now we simply assume that agents live forever, and people have to define a method to avoid this.

**Pull request merged**
