### PR TITLE
Add "Learning HARK" section to README

### PR DESCRIPTION
**Pull request by llorracc**
Quick response to Issue #271

### CODE REVIEW

**Comment by shaunagm** [comment]
This looks good to me.

**Comment by llorracc** [comment]
Thx for reviewing.  I've initiated an update from the master branch before merging, and Travis has to run before I can merge it in.  If you see it before I do (after Travis finishes), just go ahead and merge.  (Is there a way to get Travis to send an email or something when it has finished its checks?)

**Comment by shaunagm** [comment]
Yes, we can configure email notifications for Travis, [see here](https://docs.travis-ci.com/user/notifications/#configuring-email-notifications).  Options:

```
You can change the conditions for any notification channels by setting the on_success or on_failure flag to one of:

always: always send a notification.
never: never send a notification.
change: send a notification when the build status changes.
```

**Comment by mnwhite** [comment]
"Installing HARK with pip does not give you full access to HARK's many graphical capabilities."

This sentence is not true.  pip install gives you everything in HARK.  The graphical stuff is not specific to Anaconda, merely using a graphical IPython environment.

I can merge in, and will edit the readme to fix this a bit later.

**Comment by llorracc** [comment]
Release notes: Added "Learning HARK" section to README

**Pull request merged**
