### PR TITLE
Preparation for v0.14.0 release

### PR DESCRIPTION
**Pull request by mnwhite**
Update CHANGELOG, init, pyproject.

### CODE REVIEW

**Comment by alanlujan91** [comment]
@mnwhite not your fault, something with numba was failing as of last night 

https://github.com/econ-ark/HARK/actions/runs/7734162741

**Comment by mnwhite** [comment]
Whoops @alanlujan91 , I didn't notice your comment before pushing a test rollback. Because things were working on Tuesday and not working today, I assumed it was the version number change. I guess I'll let things stew for a day or two and see if it resolves itself.

**Comment by llorracc** [comment]
Just checking in on the progress of this …



From: Matthew N. White ***@***.***>
Date: Thursday, February 1, 2024 at 15:13
To: econ-ark/HARK ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [econ-ark/HARK] Preparation for v0.14.0 release (PR #1377)

Whoops @alanlujan91<https://github.com/alanlujan91> , I didn't notice your comment before pushing a test rollback. Because things were working on Tuesday and not working today, I assumed it was the version number change. I guess I'll let things stew for a day or two and see if it resolves itself.

**Comment by mnwhite** [comment]
@llorracc Something external to HARK has been changed and it's breaking our tests. Alan thinks it's interpolation.py and that we need to remove our usage / dependency on it because it's not being maintained.

**Comment by alanlujan91** [comment]
tests are starting to pass!

**Comment by mnwhite** [comment]
Incredible!

**Comment by alanlujan91** [comment]
Outstanding check failing has to do with Documentation: @MridulS @AA-Turner help?

**Comment by alanlujan91** [comment]
@mnwhite this now passes Documentation checks, and will (hopefully) pass all other tests soon

**Pull request merged**
