### PR TITLE
Updating the Autodocs

### PR DESCRIPTION
**Pull request by DominicWC**
- [ ] Tests for new functionality/models or Tests to reproduce the bug-fix in code.
- [ ] Updated documentation of features that add new functionality.
- [ ] Update CHANGELOG.md with major/minor changes.

This pull request fixes several small documentation issues and expands the autodocs for the HARK models to make them more informative. So far ConsIndShockModel, ConsIndShockModelFast, and ConsPrefShockModel have been updated. I'm currently working on the others. It also substantially reworks the installation guide.

### CODE REVIEW

**Comment by DominicWC** [comment]
I made a small change to core.py, could someone who understands how core.py works check that it won't cause problems?

**Comment by sbenthall** [comment]
image

**Comment by sbenthall** [comment]
image

**Comment by sbenthall** [comment]
image

**Pull request merged**
