### PR TITLE
[WIP] create changelog for next release

### PR DESCRIPTION
**Pull request by MridulS**
We really ought to add changes to CHANGELOG.md whenever we make major changes/add new things to econ-ark.

### CODE REVIEW

**Comment by llorracc** [comment]
This seems like a good topic for an EEP.  

Aspirationally, we are all supposed to put a "For Release Notes: " line on any PR which does something that should be mentioned in the release notes, but we have not been doing that.  Then whoever is doing the update looks through the PR's for the release notes.  How should we change that?

**Comment by sbenthall** [comment]
Is this still WIP?

**Comment by MridulS** [comment]
I am waiting for @llorracc to the push the changes to the Impatience factor nomenclature.

**Comment by MridulS** [comment]
https://github.com/econ-ark/HARK/pull/780

**Pull request closed without merging**
