### PR TITLE
added econforge interpolation into LinearInterp and scipy interpolati…

### PR DESCRIPTION
**Pull request by gms158**
…on into CubicInterp

Please ensure your pull request adheres to the following guidelines:

- [x] Tests for new functionality/models or Tests to reproduce the bug-fix in code.
- [ ] Updated documentation of features that add new functionality.
- [ ] Update CHANGELOG.md with major/minor changes.

### CODE REVIEW

**Comment by gms158** [comment]
I temporarily removed scipy CubicInterp, since it does have minor tolerance value changes, which causes errors in the unit test. I tested scipy CubicHermiteSpline, which resulted in larger tolerance issues than CubicInterp. I removed this to at least get the base LinearInterp changes implemented. I added a try catch around the econforge linear interpolation test, since this will capture the error and should not increase runtimes. If this approach is not desirable, we can try and think of cleaner ways to do this.

**Comment by alanlujan91** [comment]
@gms158 because EconForge uses numba and numba is for speeding up array arithmetic, I wonder if the error is simply because the test is using ints and not arrays

https://github.com/econ-ark/HARK/runs/6178262613?check_suite_focus=true#step:5:558

Maybe Bilinear and Trilinear should check the type first and if inputs are ints then they should be cast as arrays?

**Comment by gms158** [comment]
Alan-
yes, I was going to look into this more tomorrow. I may or will follow
up with a question or two for you tomorrow.
-Gry

**Comment by albop** [comment]
I'm currently offline but if you want I can help review this PR next week

**Comment by gms158** [comment]
I updated the interpolation code to account for infrequent and outlier cases where the econ forge library fails when evaluating one point consisting of integers, for python 3.8 and higher.

**Comment by alanlujan91** [comment]
@albop @AMonninger did you want to review / have any comments on this before we merge it?

**Review by pat749 — APPROVED** [review]

**Review by pat749 — APPROVED** [review]
yes I have reviewed it's good to merge.

**Comment by llorracc** [comment]
@alanlujan91, do you know any reason we should not merge this?

**Comment by sbenthall** [comment]
Please add an update to the CHANGELOG describing this feature to the PR

https://github.com/econ-ark/HARK/blob/master/Documentation/CHANGELOG.md

**Comment by sbenthall** [comment]
This PR needs documentation according to the NumPy / SciPy standard:

https://github.com/econ-ark/HARK/blob/master/Documentation/contributing/CONTRIBUTING.md#guidelines

**Comment by sbenthall** [comment]
Superceded by #1151

**Pull request closed without merging**
