### PR TITLE
Attempt on Issue #103

### PR DESCRIPTION
**Pull request by JackShiqiLi**
Finished issue #103 with helps and feedback from Matthew.

### CODE REVIEW

**Comment by MridulS** [comment]
Looks good. @mnwhite any comments before merging it in?

**Comment by shaunagm** [comment]
Any sense of when you'll be able to look at this, @mnwhite?

**Comment by mnwhite** [comment]
Hopefully tomorrow.  I want to look at the comments and make sure they're
correct / neat.

**Comment by mnwhite** [comment]
This looks good to me as well.  My only request would be to capitalize the first letter of comments, and to change the word "which" in the new docstring to "that".  Strunk & White 4 life.

**Comment by llorracc** [comment]
Release note: Bug fixes

**Comment by shaunagm** [comment]
Can you write about the specific bug or the specific fix?  That's too vague for a release note.

**Comment by shaunagm** [comment]
@MridulS, tagging you in case you happen to be around, I'd love to have a more specific release note for this ASAP.

**Comment by MridulS** [comment]
Release note: Fix cubic interpolation in KinkedRSolver

**Comment by shaunagm** [comment]
Thanks @MridulS!

**Comment by mnwhite** [comment]
*Add* cubic interpolation in ConsKinkedR, not fix.  This is not a bug fix,
it's new functionality.

**Pull request merged**
