### PR TITLE
Update travis to check for py3.8 and clean up setup.py

### PR DESCRIPTION
**Pull request by MridulS**
I have updated travis to test the code against with py3.8 (the latest python release), we should keep on adding the latests releases to prevent breakage of code (like what happened with conda). 
I have also moved all the metadata to setup.cfg from setup.py (setup.cfg was just present in our codebase but we weren't using it). This will clean up setup.py and make it easier going forward when making new releases and easier to debug.

### CODE REVIEW

**Comment by MridulS** [comment]
On importing HARK in python <3.6, the prompt will give this warning to the user.


```
Python 2.7.16 (default, Nov  9 2019, 05:55:08) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.32.4) (-macos10.15-objc-s on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import HARK
Econ-Ark v0.10.4 will be the last supported version for Python 2.7, please upgrade you system to the latest release, read more at https://www.python.org/doc/sunset-python-2/
```

**Comment by sbenthall** [comment]
Do you want a review on this?

**Comment by MridulS** [comment]
@sbenthall yeah :)

**Comment by sbenthall** [comment]
Looks great. Merging.

**Pull request merged**
