### PR TITLE
fix checkConditions refactor in ConsIndShockModel

### PR DESCRIPTION
**Pull request by MridulS**

### CODE REVIEW

**Comment by MridulS** [comment]
@sbenthall I merged this in to make DemARK travis happy but can you have a look here?

**Comment by sbenthall** [comment]
I see. Thank you

**Comment by MridulS** [comment]
@sbenthall all good here?

**Comment by llorracc** [comment]
I think so -- the revised BST notebook works with the new candidate release.

If we don't find any problems in the next day or two, I think the candidate release should  become a "real" release.

**Comment by sbenthall** [comment]
I worked out one more bug related to this in #546.
In my view it's good to go.

**Pull request merged**
