### PR TITLE
remove cstwMPC from HARK codebase, bye bye

### PR DESCRIPTION
**Pull request by MridulS**
closes https://github.com/econ-ark/HARK/issues/449 https://github.com/econ-ark/HARK/issues/415 

cstwMPC stays as a REMARK and datasets moved to HARK.datasets.

### CODE REVIEW

**Comment by llorracc** [comment]
I think we should let @mnwhite actually execute the merge, just to give him the satisfaction of finally accomplishing a long-sought goal.  But @sbenthall can review first.

**Comment by sbenthall** [comment]
this passes my review.
@mnwhite please do the honors at your convenience

**Comment by mnwhite** [comment]
Hold on, trying to come up with the perfect meme to link here.  This is
important.

**Comment by llorracc** [comment]
@mnwhite you might lose your privileges to merge this if you don't find a meme fast enough!

**Comment by mnwhite** [comment]
Yeah just go ahead.

**Pull request merged**
