### PR TITLE
[WIP] Pre-commit

### PR DESCRIPTION
**Pull request by alanlujan91**
Please ensure your pull request adheres to the following guidelines:

- [ ] Tests for new functionality/models or Tests to reproduce the bug-fix in code.
- [ ] Updated documentation of features that add new functionality.
- [ ] Update CHANGELOG.md with major/minor changes.

### CODE REVIEW

**Review by MridulS — APPROVED** [review]
LGTM for now, we can always revisit the config.

This PR will probably result in a lot of other merge conflicts in other PRs so before maybe merging that should be taken into account.

**Comment by llorracc** [comment]
@alanlujan91 would merging this make pre-commit the default, or would the result be a situation like the one we discussed earlier in which additional steps would be necessary to activate it?  And, if the latter, would the pre-commit automation be something specific to whatever conda env you were in when you set it up?  So, then, we could each have a conda env in which precommit was activated, and one in which it was not...

**Comment by alanlujan91** [comment]
@llorracc the latter, it would need some steps to activate it
we could have different environments, but the steps to activate it is not to just have some libraries in the environment, you also have to run some commands

**Comment by alanlujan91** [comment]
Superseded by #1225

**Pull request closed without merging**
