### PR TITLE
Documentation fix AMonninger

### PR DESCRIPTION
**Pull request by AMonninger**
Fixing documentation by
- Updating links
- Adding ARKitecture as an additional documentation page to summarize the structure of econ-ark repositories + having part of the manual in the documentation directly
- Updating links in example notebooks
- Updating symlinks (figures appear in documentation)

To do:
- FashionVictimModel: It is in https://github.com/janrosa1/DemARK/tree/master/notebooks, but does not run yet. If updated and uploaded check link in HARKmanual + https://github.com/econ-ark/HARK/blob/master/examples/Journeys/Journey_1_PhD.ipynb

### CODE REVIEW

**Comment by AMonninger** [comment]
Files are ready to review. Attention needs 
- the new ARKitecture.md file for wording and typos 
- the notebooks. I updated links and deleted empty cells. As I have done it a while ago, I don't know if it would overwrite other changes as well.

All other files are simple documentation fixes.

**Comment by aniecon** [comment]
Hi Adrian,
I have looked over ARKitecture.md. Looks fine to me and apart from the typo 'varibles', everything seems okay.
Ani

**Comment by sbenthall** [comment]
This is a related documentation issue:
https://github.com/econ-ark/HARK/issues/1147

We are missing API documentation pages for many of the more recently introduced modules:

https://hark.readthedocs.io/en/latest/reference/index.html

https://github.com/econ-ark/HARK/tree/master/Documentation/reference/ConsumptionSaving

**Comment by AMonninger** [comment]
@sbenthall : Missing API is true for tools as well. Will add it, too.

**Comment by alanlujan91** [comment]
With `jupytext` being so central to how we manage our notebooks, why is it not a required dependency? Or at least a dev dependency to make sure anyone making changes to notebooks creates the correct environment. @llorracc @sbenthall

**Review by alanlujan91 — COMMENTED** [review]
I think you are still missing changes to `examples/ConsPortfolioModel/example_ConsPortfolioModel.py`

**Comment by llorracc** [comment]
https://github.com/econ-ark/HARK/pull/1154#issuecomment-1213511501

@alanlujan91, I think the reason jupytext is not a dependency is that it is a jupyter lab extension, not just a python package, and I don't know how to make a jupyter lab extension be a dependency.

**Comment by alanlujan91** [comment]
> [#1154 (comment)](https://github.com/econ-ark/HARK/pull/1154#issuecomment-1213511501)
> 
> @alanlujan91, I think the reason jupytext is not a dependency is that it is a jupyter lab extension, not just a python package, and I don't know how to make a jupyter lab extension be a dependency.

I think it can be installed like any other python package `pip install jupytext`. 

According to their [install documentation](https://github.com/mwouts/jupytext) `jupytext` is a package that includes the plug in compatible with `jupyterlab >= 3.0`. You only need to install it as a `jupyterlab` extension if you have `jupyterlab 2.x`.

**Comment by AMonninger** [comment]
@alanlujan91 : good catch. Added the last py file.
Shall we add jupyterlab to the requirements now or leave it as is?
Otherwise this should be ready to merge

**Comment by alanlujan91** [comment]
> @alanlujan91 : good catch. Added the last py file. Shall we add jupyterlab to the requirements now or leave it as is? Otherwise this should be ready to merge

I would be in favor of adding `jupyterlab` as a dependency and `jupytext` as a development environment dependency.

**Comment by llorracc** [comment]
@AMonninger, @alanlujan91 

I see there is now a message "Still in Progress?  Convert to draft" in the sidebar under "Reviewers":

https://github.com/econ-ark/HARK/pull/1154#partial-discussion-sidebar

If this is not ready to merge, let's try the "convert to draft" option.  Otherwise, please mark it as "ready to merge"

**Review by alanlujan91 — APPROVED** [review]

**Pull request merged**
