### PR TITLE
Delete stuff called old

### PR DESCRIPTION
**Pull request by llorracc**
There was a file called cstwMPCold.py which presumably is old and should be deleted.  Same for a parms file.

### CODE REVIEW

**Comment by pkofod** [comment]
if merged, this closes https://github.com/econ-ark/HARK/issues/179

**Comment by mnwhite** [comment]
I'm merging today.

**Comment by shaunagm** [comment]
Hi @llorracc , I'm going through PRs and adding a "needs release notes" label. Can you provide a one sentence summary of your changes, ideally by editing the issue itself (as opposed to leaving a comment), clearly labeled with "For release notes" or similar? Remember to specify if there are breaking changes in the PR.

I'm not going to leave a comment like this on every merged PR of yours, but you can find a full list (well, full once I'm done tagging) [here](https://github.com/econ-ark/HARK/pulls?q=is%3Apr+label%3A"needs+release+notes"+author%3Allorracc).

**Comment by llorracc** [comment]
Delete some old/outdated files that nobody was using

For release notes: Do not mention.

**Comment by llorracc** [comment]
Release notes: General cleanup of old and superseded versions

**Pull request merged**
