### PR TITLE
SmallOpenEconomy test

### PR DESCRIPTION
**Pull request by sbenthall**
A test for the SmallOpenEconomy class.

In this PR, I've tried to write the test but could not get it to work.
I'll need to ask @mnwhite how to fix it in our weekly meeting if he doesn't respond before then.

### CODE REVIEW

**Comment by mnwhite** [comment]
What happens when you run it?

**Comment by sbenthall** [comment]
https://gist.github.com/sbenthall/7999f2dbdd2c7b71dae09a4459d9f747

**Comment by mnwhite** [comment]
Should be fixed now.

**Comment by sbenthall** [comment]
Thanks, Matt.

**Pull request merged**
