### PR TITLE
MAINT: bump up doc build pipeline to py3.11

### PR DESCRIPTION
**Pull request by MridulS**

### CODE REVIEW

**Comment by MridulS** [comment]
There is a new interpolation tagged release on github https://github.com/EconForge/interpolation.py/releases/tag/v2.2.5 but it's not available on pypi/conda. We need to wait for it to be up on pypi/conda.

**Comment by AA-Turner** [comment]
[Conda](https://github.com/conda-forge/interpolation-feedstock) has [2.2.5](https://anaconda.org/conda-forge/interpolation) but [PyPI doesn't](https://pypi.org/project/interpolation/#history) -- see https://github.com/EconForge/interpolation.py/issues/109.

A

**Comment by Mv77** [comment]
Hey,

Reviving this because Pablo released `interpolation` 2.2.6 in pypi a few days ago: https://pypi.org/project/interpolation/#history

This might unlock python 3.11?

**Comment by MridulS** [comment]
continued in https://github.com/econ-ark/HARK/pull/1415, let's try with python 3.12 :)

**Pull request closed without merging**
