### PR TITLE
adds constructor for LogNormal distribution using mean and std

### LINKED ISSUE #637: Constructor for lognormal distribution that takes average and variance
See #519 and #611 

In ConsPortfolioModel (and possibly elsewhere), there are places where there is duplicate code computing a Log Normal `mu` and `sigma` from a given average and variance.

https://github.com/econ-ark/HARK/blob/master/HARK/ConsumptionSaving/ConsPortfolioModel.py#L243-L261

Rather than doing this twice in the model code, it would be better to have an alternative constructor for the lognormal distribution that took these values directly.

### PR DESCRIPTION
**Pull request by sbenthall**
fixes #637

- [x] Tests for new functionality/models or Tests to reproduce the bug-fix in code.
- [x] Updated documentation of features that add new functionality.
- [x] Update CHANGELOG.md with major/minor changes.

### CODE REVIEW

**Comment by sbenthall** [comment]
Could I ask you to please review this @Mv77 ? 

It relates to your work on #832 . Reviewing that code reminded me that there was this opportunity to make things a little more brief/direct by adding to the Lognormal distribution class.

**Comment by Mv77** [comment]
Looks great.

Sorry, you had asked me to do it but I was sorting out other things before getting to it.

**Comment by sbenthall** [comment]
No worries it sounded like you had an exam you were working on.

**Comment by sbenthall** [comment]
Because we are short staffed, with @mnwhite on break, I'll take @Mv77 's review as sufficient for acceptance of this PR.

If @mnwhite, @MridulS , or @llorracc have any objections to this policy, let me know; I certainly don't want to overstep.

**Pull request merged**
