### PR TITLE
Edits to the general income process model notebook

### PR DESCRIPTION
**Pull request by dedwar65**
Please ensure your pull request adheres to the following guidelines:

- [ ] Tests for new functionality/models or Tests to reproduce the bug-fix in code.
- [ ] Updated documentation of features that add new functionality.
- [ ] Update CHANGELOG.md with major/minor changes.

### CODE REVIEW

**Comment by alanlujan91** [comment]
@dedwar65 the notebooks in `Documents\example_notebooks` are symlinks to the notebooks in the `examples` directory. I have added a symlink instead of the file that you had put there, but let me know if you had a different intent

**Comment by dedwar65** [comment]
@alanlujan91 I didn't realize this, but I will now make edits from the `examples` directory from here on out. Thanks for the heads up.

**Comment by alanlujan91** [comment]
@dedwar65 are you done with this PR?

**Comment by dedwar65** [comment]
@alanlujan91 Yes. I would like to see what the "hark.readthedocs.io" page looks like after this PR is merged in. I opened an issue about an equation not rendering at the site that I am not sure if my edits will correct.

**Review by alanlujan91 — APPROVED** [review]

**Comment by alanlujan91** [comment]
@dedwar65 you can check now!

**Pull request merged**
