### PR TITLE
Remove trailing whitespace

### PR DESCRIPTION
**Pull request by jasonaowen**
Spaces and tabs at the end of a line have no functional or syntactic benefit, and can be distracting. Various editors (and various configurations of editors) can handle trailing whitespace differently; some will automatically strip trailing whitespace from all lines of a file on saving, which can leads to needlessly large diffs.

Remove all trailing whitespace from our Python and (non-generated) Markdown files, by running (effectively) the following shell script to use sed to edit each file in place:

```bash
for f in $(git ls-files '*.py' '*.md')
do
  sed -i 's/[[:space:]]*$//' "$f"
done
```

### CODE REVIEW

**Comment by jasonaowen** [comment]
You can confirm that these changes are, in fact, whitespace-only by using the slightly-difficult-to-access, whitespace-ignoring view in GitHub: https://github.com/econ-ark/HARK/pull/159/files?w=1 .

**Comment by mnwhite** [comment]
Now I want to know what other flags I can pass to GitHub's PR viewer...

**Comment by jasonaowen** [comment]
@mnwhite adding `?w=1` to the end is the only secret query parameter I know of! I'd love to learn about any others, if they exist.

**Comment by kfogel** [comment]
`?c=on` tells you if the change is correct or not.  This flag is not widely advertised.

**Comment by jasonaowen** [comment]
@kfogel hah!

In other news, TIL that the feature of a whitespace-ignoring view, once poorly documented and mostly unexposed in the UI, is now all grown up! As of May 1st of this year, there is a way to toggle this in the UI: https://blog.github.com/2018-05-01-ignore-white-space-in-code-review/ . Good job, GitHub!

**Pull request merged**
