### PR TITLE
Rename pmf and X

### PR DESCRIPTION
**Pull request by alanlujan91**
See #1051, #1159

### CODE REVIEW

**Comment by sbenthall** [comment]
I like it. Changelog update?

**Comment by alanlujan91** [comment]
PR https://github.com/econ-ark/DemARK/pull/187 fixes DemARK's after this PR is merged.

**Comment by llorracc** [comment]
@alanlujan91, @MridulS 

Do we have a way to check whether any REMARKs might be broken?  

In principle, REMARKs should all have version control on them so should not break.  In practice, I doubt that they all do (or do so correctly).

**Comment by llorracc** [comment]
@MridulS,

To broaden my prior point, if I'm not mistaken, at the moment our procedure is to run DemARK checks nightly by running against the master branch of the development HARK repo.  Would it be easy to set things up so that the DemARKs are also tested against any new PR's?  Or, at least, could we somehow automatically remind the poster of a new PR to check DemARKs (and maybe REMARKs)?

**Pull request merged**
