### PR TITLE
Add more parameter types to `Parameters`

### PR DESCRIPTION
**Pull request by Mv77**
I have been playing with the `core.Parameters` class and really like it. One limitation is that it restricts the class of parameters that can be time-varying. This PR adds support for a few more classes: booleans, distributions, and functions.
 
You can imagine passing time-varying parameters of this class if, for instance you want:
- To indicate whether an agent is `retired = True | False` for some meaningful change in its income process.
- To have a time varying distribution for income shocks. Maybe this period they are normal, and the next they are lognormal.
- To have a time varying tax function.

I have used this class in my ongoing work and have been very happy with it.

- [x] Tests for new functionality/models or Tests to reproduce the bug-fix in code.
- [x] Updated documentation of features that add new functionality.
- [x] Update CHANGELOG.md with major/minor changes.

### CODE REVIEW

**Comment by Mv77** [comment]
@alanlujan91 should this change be reflected in other parts of the code like, say, https://github.com/econ-ark/HARK/blob/6a73c4f32a52ff9404f731761c3b754c1f85d650/HARK/core.py#L95 ?

**Comment by Mv77** [comment]
Not sure this needs a test?

**Comment by alanlujan91** [comment]
@MridulS is there a way for `pre-commit` to automatically upload changes?

**Comment by MridulS** [comment]
There is [pre-commit.ci](https://pre-commit.ci/) but it makes changes to the PR branch and you need to make sure the contributors are pulling in all changes before making any new changes locally. I would just strongly suggest to new contributors to use pre-commit locally :)

**Comment by alanlujan91** [comment]
well, somehow my pre-commit is different than the one in github actions?? @MridulS

**Comment by Mv77** [comment]
MAC hates me. And I hate it too.
It's the same tests as in https://github.com/econ-ark/HARK/pull/1415

Will come back to this when that's merged

**Comment by sbenthall** [comment]
This PR was blocked by some unrelated logistical thing.
Now its only conflict is the CHANGELOG.

Can this be fixed and merged now?

**Comment by mnwhite** [comment]
I'll try to look at this in the morning. I thought it still had a
(non-trivial) outstanding issue.

**Comment by mnwhite** [comment]
GitHub is hanging on its automatic merge check. I'm trying to get this in now.

**Pull request merged**
