### PR TITLE
Added updateLbrCost Function

### PR DESCRIPTION
**Pull request by rkcah**
Added the second feature as mentioned in #427 

Included the following three changes:

1. Removed `LbrCost` from `time_vary` class definition
2. Added `self.updateLbrCost()` to the `update()` function
3. Added the function `updateLbrCost`

### CODE REVIEW

**Comment by mnwhite** [comment]
Great!  Can you edit ConsumerParameters to have the example dictionaries use this method?  Note that for the infinite horizon example, LbrCostCoeffs will only need one element-- there's only one (infinitely repeated) period, so any function beyond f(t) = a would be very silly!  The short lifecycle example can have two coefficients, just to demonstrate this function.

**Comment by rkcah** [comment]
I have added the required changes in `ConsumerParameters.py`. Please have a look and let me know if something else is required to be done.

**Comment by mnwhite** [comment]
Not quite.  The old LbrCost was [0.36], and your LbrCost-generating method takes the exp of the polynomial function (as it should), so the new LbrCostCoeffs should have log(0.36) ~= -1.0 for its constant term.

In the lifecycle example, my point was that you should choose a constant and linear term and explicitly write them.  Just use [-2.0, 0.4]. It doesn't make sense to arbitrarily use the same coefficient for the constant and linear coefficient.

**Comment by rkcah** [comment]
Changed the values as you suggested. I was a bit confused about which values to give so I just kept the existing values. Thanks for pointing out the error.

**Comment by mnwhite** [comment]
Great!

**Pull request merged**
