### PR TITLE
Deal with cases when the agent wants to short

### PR DESCRIPTION
**Pull request by Mv77**
This implements the solution proposed by @mnwhite  in #741 for dealing with cases where the agent wants to hold less than a 0% share of the risky asset.

I did some testing and it seems to be well behaved. The approach assumes that as long as the FOC at s=0 is negative, the agent wants to hold less than 0. I guess it will break if one considers non-concavities in the value function?

I got rid of the try-except block as @mnwhite suggested.

### CODE REVIEW

**Comment by llorracc** [comment]
> I guess it will break if one considers non-concavities in the value function?

Yes; but anything will break under those circs.  We may need to handle this in the future (esp when trying to have a discrete-continuous problem jointly with the portfolio problem) but that's a problem for another day.

**Comment by mnwhite** [comment]
Yeah, the code assumes a single-crossing property / monotone FOC, but
that's consistent with most of our other solvers, which assume that the
(marginal) value function being fed to it from solution_next came from the
solution to the same model and thus is guaranteed to have certain
properties.

A while back I wrote a "robust" ConsIndShock solver that used Giu Fella's
method for handling non-concave value functions.  Just like my attempt at
implementing his discrete labor supply choice model with that method, it
put the "bust" in "robust".  18 months ago I began work with Fedor Iskhakov
on an improved method.

Anyway, thanks for doing this so fast, I'll take a look soon.

**Comment by Mv77** [comment]
> 
> 
> > I guess it will break if one considers non-concavities in the value function?
> 
> Yes; but anything will break under those circs. We may need to handle this in the future (esp when trying to have a discrete-continuous problem jointly with the portfolio problem) but that's a problem for another day.

Yes, exactly. Since I know we will eventually have to deal with this, I just want to keep a mental list of where things might break.

**Comment by mnwhite** [comment]
Yes, this is exactly correct.  And I guess I had already handled the 100% constraint, now labeled as `top_constraint`; that might be why I thought I dealt with the 0% constraint as well.  Nice work.

**Pull request merged**
