### PR TITLE
Revamp documentation on RTD

### PR DESCRIPTION
**Pull request by MridulS**
- API documentation is now divided into ConsumptionSaving and tools
- Cleaner interface to navigate through the docs website
- Markdown files can be used for documentation

### CODE REVIEW

**Comment by MridulS** [comment]
TODO:
- [ ] Use the README to mirror content on the documentation website
- [ ] Link developer documentation, move Collaboration guide to documentation, installation instructions should also be moved inside Documentation/

**Comment by sbenthall** [comment]
Sounds super. I'll test locally and rendered to a test RTD site.

One question: currently there is a `Documentation/` and a `doc/` directory.
My preference would be to consolidate all this into the `doc/` directory.
This seems to be more standard across Python packages.

Is there any reason not to do that?

**Comment by sbenthall** [comment]
Is this WIP ? I see TODOs. I'll review whenever you want.

**Comment by MridulS** [comment]
@sbenthall yeah its WIP right now, I wanted to get reviews in the meeting today and then I will add more stuff to this.

**Comment by MridulS** [comment]
> One question: currently there is a Documentation/ and a doc/ directory.
My preference would be to consolidate all this into the doc/ directory.
This seems to be more standard across Python packages.

> Is there any reason not to do that?

looks like the doc/ directory was introduced during the documentation restructure and yes, all of the documentation should live in one folder (Documentation or doc)

**Comment by MridulS** [comment]
To discuss in meeting after merge - CoC, currently we just link to the one on NumFOCUS, we should atleast copy it back to our documentation (NF requires all projects to have one?)

**Pull request merged**
