### PR TITLE
add arguments to discretize

### PR DESCRIPTION
**Pull request by alanlujan91**
Please ensure your pull request adheres to the following guidelines:

- [x] Tests for new functionality/models or Tests to reproduce the bug-fix in code.
- [x] Updated documentation of features that add new functionality.
- [x] Update CHANGELOG.md with major/minor changes.

### CODE REVIEW

**Comment by sbenthall** [comment]
Looks good. Changelog?

**Comment by sbenthall** [comment]
Docs too please

**Comment by alanlujan91** [comment]
TODO: Apply to cstwMPC

**Comment by mnwhite** [comment]
It looks like this PR was forgotten about. I'm merging after tests finish running.

**Pull request merged**
