### PR TITLE
UtilityFuncCRRA

### PR DESCRIPTION
**Pull request by alanlujan91**
This PR creates an object oriented CRRA utility function to better organize namespaces and add formal structure to models. 

- [x] Tests for new functionality/models or Tests to reproduce the bug-fix in code.
- [x] Updated documentation of features that add new functionality.
- [x] Update CHANGELOG.md with major/minor changes.

### CODE REVIEW

**Comment by sbenthall** [comment]
This looks like a good step forward to me!

**Comment by alanlujan91** [comment]
To do from @llorracc: look for standardized function representation (with derivatives and inverses) in other python libraries

**Comment by alanlujan91** [comment]
from scipy: https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.PPoly.html#scipy.interpolate.PPoly
from sympy: https://docs.sympy.org/latest/guides/custom-functions.html#differentiation

There does not seem to be a standard for mathematical functions.

**Comment by alanlujan91** [comment]
To do: Think of design for CRRA(CD) and/or CRRA(CES).

**Comment by sbenthall** [comment]
Looks like there's significant overlap between this PR and #1177 

This looks like a simpler feature, and unless there's some good reason I'm not thinking of, it would be best to finish this one in its own PR.

**Comment by sbenthall** [comment]
Fix merge conflict please.

**Comment by sbenthall** [comment]
My bad ...

**Comment by sbenthall** [comment]
@llorracc : advocates aligning this syntax with dolo's

**Comment by alanlujan91** [comment]
Would like to have all *econ* utility functions in `HARK.utilities`, but I think it's useful for *econ* `UtilityFunction` objects to inherit from `MetricObject` so they can be compared, ie what is the distance between utility functions? However, when I add `from HARK.core import MetricObject` into `HARK.utilities` I get a circular reference error because `core.py` inherits from `utilities.py`. 

I would like to propose that the file `utilities.py` contains only classes/methods that pertain to *econ* utility functions, and everything else that is more of a *programming* utility to go into a file called `tools.py` or something like that. This would avoid the circular reference.

**Comment by alanlujan91** [comment]
# TODO : labeled goods

**Comment by sbenthall** [comment]
@alanlujan91 See merge conflicts and test failures.

Punt the broader scope issues to #1035.
Lots of good stuff in this PR as is.

**Comment by alanlujan91** [comment]
now addresses #1188

**Comment by alanlujan91** [comment]
Changes in this PR: 

- Move *econ* utilities to `rewards.py`.
- Rename parameter `gam` to `rho` in `CRRAutility` and derivatives. 
- Fix `ZeroDivisionError` in all utility functions. 
- Create `cobb_douglas`, `cobb_douglas_p`, `cobb_douglas_pp`, and `cobb_douglas_pn` functions. 
- Create `const_elast_subs` and `const_elast_subs_p` functions. 
- Implement abstract `UtilityFunction` class. 
- Implement `UtilityFuncCRRA` class with derivative and inverse. 
- Implement `UtilityFuncCobbDouglas` with derivative. 
- Implement `UtilityFuncCobbDouglasCRRA`. 
- Implement `UtilityFuncConstElastSubs`. 
- Replace instances of `CRRAutility` with `UtilityFuncCRRA` throughout codebase.

**Comment by sbenthall** [comment]
I'll review this and merge if I don't see any issues.

**Comment by sbenthall** [comment]
Great work! Merging.

**Pull request merged**
