### PR TITLE
adding IndShockConsumerTypeFast

### PR DESCRIPTION
**Pull request by alanlujan91**
Please ensure your pull request adheres to the following guidelines:

- [x] Tests for new functionality/models or Tests to reproduce the bug-fix in code.
- [x] Updated documentation of features that add new functionality.
- [N/A] Update CHANGELOG.md with major/minor changes.

This PR can only be merged after #774. 

Very close to working version of a fast IndShockConsumerType. Passes eye test on IndShockConsumerType.ipynb example notebook, but still fails some tests that I need to look into.

### CODE REVIEW

**Comment by alanlujan91** [comment]
Tests not passing: 

```
>       self.assertAlmostEqual(c_m[500], 0.7772637042393458)
E       AssertionError: 0.7774503031412109 != 0.7772637042393458 within 7 places (0.0001865989018651204 difference)

>       self.assertAlmostEqual(c_m[500], 1.4008090582203356)
E       AssertionError: 1.4008094278419174 != 1.4008090582203356 within 7 places (3.6962158178610593e-07 difference)

>       self.assertAlmostEqual(c_m1[0], 0.8527887545025995)
E       AssertionError: 0.8528115261262652 != 0.8527887545025995 within 7 places (2.2771623665707175e-05 difference)

>       self.assertAlmostEqual(IndShockExample.solution[0].mNrmSS, 1.5488165705077026)
E       AssertionError: 1.5455777984337853 != 1.5488165705077026 within 7 places (0.0032387720739173176 difference)

>       self.assertAlmostEqual(LifecycleExample.solution[5].cFunc(3).tolist(), 2.129983771775666)
E       AssertionError: 2.1306421962827153 != 2.129983771775666 within 7 places (0.0006584245070495598 difference)

>       self.assertAlmostEqual(CyclicalExample.solution[3].cFunc(3).tolist(), 1.5958390056965004)
E       AssertionError: 1.5970793161392047 != 1.5958390056965004 within 7 places (0.0012403104427043399 difference)
```

Although this now runs as expected, I am having some small and some not so small deviations from what the solutions of the standard HARK model are. The solution however, is twice as fast or better after 1st run (546ms vs 142ms on my computer when `CubicBool=True` and `vFuncBool=True`)

**Comment by alanlujan91** [comment]
Only 2 `failed` now, with small differences. Additionally, benchmarking on my laptop when `CubicBool=True` and `vFuncBool=True` follows:
Fast: `170 ms ± 32.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)`
Standard: `414 ms ± 9.89 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)`

```
============================== short test summary info ==============================
FAILED HARK/ConsumptionSaving/tests/test_IndShockConsumerTypeFast.py::testBufferStock::test_infinite_horizon - AssertionError: 1.0036643401519418 != 1.0036279936408656 within 7 places (3.634651107620179e-05 difference)

FAILED HARK/ConsumptionSaving/tests/test_IndShockConsumerTypeFast.py::testIndShockConsumerTypeFastCyclical::test_cyclical - AssertionError: 1.5958389403194548 != 1.5958390056965004 within 7 places (6.53770455549818e-08 difference)
```

**Comment by llorracc** [comment]
@alanlujan91 check whether adding more gridpoints fixes the problem and if so change the tolerance so that it does not fail any more with the original set of gridpoints.

**Comment by alanlujan91** [comment]
This finally passes all tests locally! Benchmarking on my laptop when `CubicBool=True` and `vFuncBool=True` follows:
Standard: `424 ms ± 13.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)`
Fast: `112 ms ± 5.91 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)`

**Comment by alanlujan91** [comment]
Ha I guess I did speak too soon... Interestingly, when I run just the test for my code `test_IndShockConsumerTypeFast.py`, it passes, but when it runs along with every other test, it fails? @MridulS any ideas? The tests seem to fail at simulation, but my code doesn't change any of the simulation process. Maybe it has something to do with how I'm inheriting from other tests.

**Comment by MridulS** [comment]
Can you change the line 
```
self.base_params = init_idiosyncratic_shocks
```
to 
```
self.base_params = copy(init_idiosyncratic_shocks)
```
in `testBufferStock` in `test_IndShockConsumerType.py` file.

This should fix it.

Also to make test names a little more distinct can you rename `testBufferStock` to something like `testBufferStockFast` in `test_IndShockConsumerTypeFast.py` file.

**Pull request merged**
