### PR TITLE
Fix external links in documentation

### PR DESCRIPTION
**Pull request by AA-Turner**
cc: @MridulS, @DominicWC

This PR updates external links, following running the [``linkcheck`` builder](https://www.sphinx-doc.org/en/master/usage/builders/index.html#sphinx.builders.linkcheck.CheckExternalLinksBuilder).

Additional problems include:

* The SSL certificate for https://www.econ2.jhu.edu expired in August 2022. Links to that website should be updated to a new site where SSL works properly.
* ``doi.org`` & Wiley don't seem to like automatic probing, but I used manual verification here.
* The [installation guide](https://docs.econ-ark.org/guides/installation.html) reccomends Atom, which is no longer supported by GitHub.

A

### CODE REVIEW

**Comment by MridulS** [comment]
> The SSL certificate for https://www.econ2.jhu.edu/ expired in August 2022. Links to that website should be updated to a new site where SSL works properly.

All links from https://www.econ2.jhu.edu seems to have moved. I remember @llorracc mentioned something along these lines.

>    The [installation guide](https://docs.econ-ark.org/guides/installation.html) reccomends Atom, which is no longer supported by GitHub.

Yeah we should fixed that, and I think we anyway need to audit the instructions. They haven't been touched in a while and we should make sure that they still work. Maybe @DominicWC you can look into this?

**Comment by DominicWC** [comment]
This seems to fix the broken links between the quick start guide and the latex issues. Is there any way to move the pages in the guide section to the overview and examples section, so that anyone reading it doesn't miss it accidentally?

The installation guide could just leave out the sections on atom/spyder respectively. Most users will have an IDE already. We could maybe mention that they should get an IDE if they don't have one already. Everything with PIP looks fine, but I'll test the section on Anaconda.

**Comment by MridulS** [comment]
> This definitely fixed the broken links between the quick start guide and the latex issues. Is there any way to move the pages in the guide section to the overview and examples section, so that anyone reading it doesn't miss it accidentally?

Yeah we can do that, maybe we should do that in an another PR? We can do the re-organizing bits separately.

**Comment by DominicWC** [comment]
Everything in this current pull request looks good to me, we can make other changes in a separate PR. The whole docs page could use some reorganizing and trimming/additions, but that's a separate change.

**Comment by AA-Turner** [comment]
> This definitely fixed the broken links between the quick start guide and the latex issues. Is there any way to move the pages in the guide section to the overview and examples section, so that anyone reading it doesn't miss it accidentally?

@DominicWC -- Please would you be able to elaborate a little on your desired position here?

I tried (briefly) to explain the rationale for where pages go in PR #1302 -- there is an intentional difference between 'guide' style content and 'explanation' style content. These distinctions come from the [Diátaxis](https://diataxis.fr/) framework, and help provide a discriminator between different types of content.

We should make all of these more discoverable, but I'm curious if the layout and organisation of the pages themselves is unhelpful or counter-productive -- and what we could do to improve that.

A

**Comment by DominicWC** [comment]
When on to the main page, the only obvious direction is to the page "overview" which is part of the "overview and examples" section of the page. A reader gets a brief introduction and overview of HARK before immediately going into the examples section. As a reader, it certainly feels like the documentation simply skipped any information on how to install it. The only way that a reader actually finds it is if they, 
1. notice the guide bar at the top rather than the big section navigation window on the side
2.  Either piece together that the "guide" section has this relevant information on how to use hark that the section they're currently in doesn't or decides to explore the whole documentation page

I think it would make more sense for the user if we did at least one of the following:
a. included the "Quick start guide" as a part of the "introduction to hark" section
b. started in the "guide" section before transitioning to the "overview and example" section
c. Included a way to jump between the three main sections from the sidebar, and had some way of indicating that installation information was included in that section (Maybe by saying Guide(installation and contribution) or by including a dropdown menu for it).

**Comment by AA-Turner** [comment]
@DominicWC -- are your concerns allayed by the new grid cards on the [landing page](https://docs.econ-ark.org/)? I also included a link to the installation guide in the new 'quick links' section.

**Comment by DominicWC** [comment]
I think we might want to rename the "Arkitecture" tab to "Arkitecture and examples", so that people know examples are in that tab. Otherwise, I think its really good.

**Comment by MridulS** [comment]
I'll go ahead and merge this one, we can discuss the organization bits in another issue/PR :)

**Pull request merged**
