### PR TITLE
Tackle HARK issue #359

### PR DESCRIPTION
**Pull request by JackShiqiLi**
Overwritten preSolve() in PerfForesightConsumerType to call checkConditions().
Previously, checkConditions() were defined but not called before SolveAgent(), now setting PermGroFac such that PermGroFac/Rfree > 1 will output the message in checkConditions().
Problem: checkConditions() does not stop the solving process, so the RuntimeWarnings mentioned in issue #359 still appear. Maybe we should stop the solving process if the conditions are not met?

### CODE REVIEW

**Comment by JackShiqiLi** [comment]
With a further look I found that my code was out of date, in the code here there is a preSolve() overwritten at line 1540, except that it does not call checkConditions(), so simply add checkConditions() to preSolve() will do the work.

**Comment by llorracc** [comment]
It looks like this test is performed in all cases.  It only makes sense in the case of the infinite horizon solution of the model.  Could you add a test for whether the user has invoked it with the appropriate values of the various "cycles" settings to require an infinite horizon solution?

**Comment by JackShiqiLi** [comment]
I think the test for the 'cycles' has already been written in the checkConditions() function at lines 1762 to 1765.
```python
    # This method only checks for the conditions for infinite horizon models
    # with a 1 period cycle. If these conditions are not met, we exit early.
    if self.cycles!=0 or self.T_cycle > 1:
        return
```
My trial in the Gentle-Intro-To-HARK-PerfForesightCRRA notebook shows that if you add another line `NewExample.cycles = 1` ( 1 can be replaced by any integers > 0) in addition to what you have mentioned in issue #359 , then a proper solution is reached with a graph. but if it sticks to 0 (the infinite horizon case), then the message 'The given type violates the Finite Human Wealth Condition; the Finite Human wealth factor value 1.01942' shows before the RuntimeWarnings.

**Comment by llorracc** [comment]
Thanks for closing this!

**Pull request closed without merging**
