### PR TITLE
Updatepresolve

### LINKED ISSUE #222: After income process parameters change, warn user to recompute .updateIncomeProcess()
It is inevitably confusing to new users that when they change some component of the income process like UnempPrb, the IndShockConsumerType consumer continues to use the old income process corresponding to the original parameterization.  We should at least have a warning to the user that they need to invoke [instance].updateIncomeProcess() to recompute the new income process.

### PR DESCRIPTION
**Pull request by pkofod**
Fixes #222 at the expense of a few more calculations each time `solve` is called. Advanced users can easily create a `MyIndShkType` and overwrite `preSolve` with a new 3-line method that doesn't update between `solve()` calls. The cost is probably negligible anyway, compared to solving the model and any post-processing you might do after solving a model.

### CODE REVIEW

**Comment by mnwhite** [comment]
This has been one of the long-demanded items (as a one line fix). Gentle
intro notebook should be updated to reflect this change. That's part of my
notebook overhaul.

**Comment by pkofod** [comment]
> This has been one of the long-demanded items (as a one line fix). Gentle intro notebook should be updated to reflect this change. That's part of my notebook overhaul.

Just verifying: you agree that this should be done and it should be done like this, right?

**Comment by mnwhite** [comment]
Yes, please.

**Comment by pkofod** [comment]
Great. Merge when you're ready :)

**Comment by llorracc** [comment]
Ultimately, we will want to define a distribution object which "stores" the parameters needed to produce its approximation (like, that it is a lognormal with mean 0.02 and standard deviation of 0.1 produced by the equiprobable method of approximation using seven nodes).  That way, the current parameters can be compared to the stored one, and the distribution computed only if it has changed.  A quicker but uglier fix would be just to have the agent object store this info (instead of having a separate distribution object for it).  

@albop

**Comment by pkofod** [comment]
> Ultimately, we will want to define a distribution object which "stores" the parameters needed to produce its approximation (like, that it is a lognormal with mean 0.02 and standard deviation of 0.1 produced by the equiprobable method of approximation using seven nodes). That way, the current parameters can be compared to the stored one, and the distribution computed only if it has changed. A quicker but uglier fix would be just to have the agent object store this info (instead of having a separate distribution object for it).

I agree that it could be done to make this slightly more efficient, but I'm wondering if the extra complexity is really worth it? I have strong doubts that re-calculating these things will be significant in the overall picture. We can try a specific implementation at some point to see if the extra complexity is worth it.

**Comment by shaunagm** [comment]
@pkofod Can you write a release note?  Thanks.

**Comment by pkofod** [comment]
Uhm yes. Something like.

"Added a call to updateIncomeProcess() in preSolve() to avoid solutions being based on wrong income process specifications if some parameters change between two solve() calls."

**Pull request merged**
