### PR TITLE
move data from cstwMPC to datasets

### PR DESCRIPTION
**Pull request by MridulS**
#618

### CODE REVIEW

**Comment by MridulS** [comment]
downstream changes to make:

KrusselSmith REMARK, import datasets

`init_infinite` in Structural-Estimates-From-Empirical-MPCs-Fagereng-et-al

**Comment by MridulS** [comment]
Micro-and-Macro-Implications-of-Very-Impatient-HHs DEMARK,  import datasets

**Comment by MridulS** [comment]
This PR makes it possible to import US Survey of Consumer Finances data by 
```
from HARK.datasets import load_SCF_wealth_weights

SCF_wealth, SCF_weights = load_SCF_wealth_weights()
```

instead of 

```
from HARK.cstwMPC.SetupParamsCSTW import SCF_wealth, SCF_weights
```

**Comment by MridulS** [comment]
@sbenthall can you have a look?

**Comment by sbenthall** [comment]
looks good!

**Pull request merged**
