### PR TITLE
Simple lint edits commits for dcegm.py

### PR DESCRIPTION
**Pull request by rsaavy**
it still gets
`dcegm.py:155:25: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
dcegm.py:161:26: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
dcegm.py:175:50: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
`

### CODE REVIEW

**Comment by llorracc** [comment]
I think we'd better leave this for @pkofod's judgment tomorrow.  Thanks!

**Comment by shaunagm** [comment]
I'm going to go ahead and merge it.  I'll flag it so we can follow up and fix the last E712 errors once we hear back from Patrick.

**Comment by llorracc** [comment]
OK, sounds good.

**Comment by pkofod** [comment]
Thanks! Wrt the other things, I'd have to check first that it works with numpy arrays.

**Pull request merged**
