### PR TITLE
implement CubicHermiteInterp

### PR DESCRIPTION
**Pull request by alanlujan91**
CubicHermiteInterp is a HARK compatible wrapper of scipy's CubicHermiteSpline

See notebook for discussion: https://github.com/alanlujan91/HARK/blob/scipyCubic/examples/Interpolation/CubicInterp.ipynb

Please ensure your pull request adheres to the following guidelines:

- [ ] Tests for new functionality/models or Tests to reproduce the bug-fix in code.
- [ ] Updated documentation of features that add new functionality.
- [ ] Update CHANGELOG.md with major/minor changes.

### CODE REVIEW

**Comment by sbenthall** [comment]
This is great work @alanlujan91 !

I would be in favor of this _replacing_ HARK's current cubic interpolator.

What happens if you do that? Do the automated tests for the library still pass?
In particular, do these unit tests for the interpolated pass?
https://github.com/econ-ark/HARK/blob/master/HARK/tests/test_interpolation.py#L46

(There are other model tests that use the interpolator.)

I wonder if it's possible to streamline the HARK interpolator interface further, but that may be out of scope of this particular PR.

**Comment by llorracc** [comment]
@mnwhite 

Could you review this per our conversation?  Basically either ask Alan to add the old interpolator as an option (easier) or describe to him the tests you'd like him to conduct to show that the new version is better in every respect (including the memory usage issue that you identified earlier).

**Comment by mnwhite** [comment]
I'll try to take a look at this. The easiest/quickest way forward is to use
the new version as CubicInterp and keep the old one with a marking of
LEGACY or OLD. If it has the same interface as the old code, then
everything should work the same. But then any project that needs the old
version for memory reasons has the option to do that:

`from HARK.interpolation import CubicInterpOLD`
`CubicInterp = CubicInterpOLD`

**Comment by alanlujan91** [comment]
> What happens if you do that? Do the automated tests for the library still pass?
> In particular, do these unit tests for the interpolated pass?
> https://github.com/econ-ark/HARK/blob/master/HARK/tests/test_interpolation.py#L46

@sbenthall I have swapped out CubicInterp for CubicHermiteInterp in `ConsIndShockModel.py` and in `test_interpolation.py`. Locally it passes all tests, waiting to see if it passes remotely.

**Comment by sbenthall** [comment]
Apologies for the slow review turnaround, @alanlujan91 .
I see there's a merge conflict on interpolation.py

Could you fix that merge conflict?

@mnwhite did you see any reason not to merge this PR?

**Comment by alanlujan91** [comment]
> Could you fix that merge conflict?

@sbenthall please see #1060. I think this is something that should be addressed on its own in a standalone PR. I will work on this but lmk if you have any suggestions.

**Comment by sbenthall** [comment]
Ok, should this PR be closed because it has been superseded by #1060?

**Pull request merged**
