### PR TITLE
Removes solveSOEMarkov, MarkovSOEType and MarkovSmallOpenEconomy

### PR DESCRIPTION
**Pull request by edmundcrawley**
These have been superceeded by classes in ConsAggShkModel

### CODE REVIEW

**Comment by edmundcrawley** [comment]
@mnwhite - ConsMarkovModel.py runs without error following this change.

**Comment by mnwhite** [comment]
Great. Should we merge this now (before the package restructuring) or after
that?

I don't want to create more work for OTS by merging changes to master now.
And I assume it's easy to re-do this PR in the new structure.

**Comment by brainwane** [comment]
@mnwhite @edmundcrawley Thanks! We should be able to do this in either order (merging this before or after #161); whoever authored the PR that gets reviewed and merged second can [rebase](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) probably pretty easily!

**Comment by jasonaowen** [comment]
I am happy to rebase #161 after this is merged; doing so is not a big deal, and we shouldn't block this on that!

**Comment by mnwhite** [comment]
Edmund: The changes for this PR are now in a different file due to the "installability" overhaul.  My recommendation is that we close this PR, then you branch off the most recent commit and recreate these deletions.

**Comment by edmundcrawley** [comment]
Matt: I've now done this and submitted a new pull request for you to review.

**Pull request closed without merging**
