### PR TITLE
comment out parallel SGU_solver, works for py3

### PR DESCRIPTION
**Pull request by MridulS**
Fixes https://github.com/econ-ark/HARK/issues/198

### CODE REVIEW

**Comment by llorracc** [comment]
@MridulS, looks like you deleted the version of the code that only worked in serial.  Could you restore it, but in comments?  In case for some reason (like a misconfigured machine) some people want to revert to it.

**Comment by MridulS** [comment]
I'll add back the sequential code after completing  https://github.com/econ-ark/HARK/pull/342 so there aren't any merge conflicts.

**Comment by llorracc** [comment]
Still looks to me like in your PR the old code has been deleted instead of commented out ...

**Comment by MridulS** [comment]
@llorracc added it back.

**Comment by llorracc** [comment]
Travis has been working on this for way too long -- I want to merge but our rules won't let me until Travis is happy ...

**Comment by MridulS** [comment]
fix the conflict, travis is happy now

**Comment by llorracc** [comment]
Thanks.  

PS.  I just saw Travis -- the actual PERSON -- get chased off the stage because he was exceeding his allotted 5 mins for a "lighting talk" at SciPy!  Just like his tool, I guess, sometimes he needs prodding ...

**Comment by shaunagm** [comment]
Pretty sure that Travis and the tool Travis are unrelated, but I support sending sad emails to scipy Travis whenever the tool doesn't work for us...

**Pull request merged**
