### PR TITLE
Fixed imports in model files

### PR DESCRIPTION
**Pull request by mnwhite**
All of the consumption-saving model files used a style of import that didn't work when the file was run directly (rather than called as a module), even though they have a __main__ block (and main() function).  This has now been fixed.

Also mostly removed extraneous file RepAgentModel.py, which seems to be an old name of ConsRepAgentModel.py.  This file now simply imports all of ConsRepAgentModel and warns the user to use that instead.

### CODE REVIEW

**Comment by mnwhite** [comment]
This addresses #182 , which was also raised by CDC today.  We can also consider deleting the main() calls of all of these files and only having them in the examples that we have users put in their working folder.

**Comment by llorracc** [comment]
My purpose in asking for the fix was to make the various modules like ConsIndShockModel.py "portable" -- so that they would run even if moved to a different filepath.  In attempting that with the revised version, I found that the lines containing "import ConsumerParameters" still did not work (from a directory other than ConsumptionSaving), but that everything worked if "import ConsumerParameters" was replaced with "import HARK.ConsumptionSaving.ConsumerParameters".  I have done that replacement not only for ConsIndShockModel.py but also for all of the other .py files in the ConsumptionSaving directory, and pushed the changes back up to the QuickImportFix branch.

**Comment by mnwhite** [comment]
Ah yes, I was running them in place.  As is, the "from . import blah"
construction did not work.

**Comment by llorracc** [comment]
For release notes: "Removed improper local package imports"

**Pull request merged**
