### PR TITLE
Changes to Gentle Introduction to HARK

### PR DESCRIPTION
**Pull request by sidd3888**
Changes made according to points mentioned in #1354

Primarily made changes to the description of the models or fixed typos. Only thing I changed in the code was to generate the plot of the model with updated parameters and then removing the pertinent code, so that the image matches the description (also detailed in the issue).

@alanlujan91 sent you an email about one of details. Ready to merge from my end once that is addressed

### CODE REVIEW

**Review by alanlujan91 — APPROVED** [review]
Great job! I made some notational changes but agree with all your changes.

**Comment by sidd3888** [comment]
A couple of things I wanted to clarify:
- I don't know if this is an accident, but the first statement of survival probability is as a constant, not as $\aleph_t$, though setting it to a constant is clarified only two paragraphs down. Switching between $\aleph$ and $\aleph_t$ may appear notationally inconsistent
- The use of $\mathsf{D}_t$ for probability of death: this notation is not used in the notebook after this. Should we be retaining it here? Just for this notebook, might suffice to say the problem ends with probability $1 - \aleph_t$
- Everytime someone runs the `NewExample` model with $\Gamma = 0.01$, the graph would revert to one without the updated parameters, as it is left for the reader to change the parameters. I can slightly change the wording here to indicate that the graph would obey the characteristics described **upon** changing the parameters

Once these things are addressed, this is good to go (but you'll have to merge them, I can't)

**Comment by alanlujan91** [comment]
@sidd3888 were you going to redo this one?

**Comment by mnwhite** [comment]
I adjusted a few words, including the age-varying notation in the first paragraph. I moved the sentence about death probability to be semicolon clause in the LivPrb sentence; it's less prominent now, as Siddarth is correct that it serves little purpose.

The existence of the reference to death probability might be a legacy of older notation. I think we used to use D for death probability and \cancel{D} for survival probability, making it more useful to actually mention death probability.

Some of the checks are now failing after adjusting text, which is surprising. I'll look into it.

**Comment by mnwhite** [comment]
It looks like it's because I cleared notebook output, but Sphinx relied on its existence. Will fix.

**Comment by mnwhite** [comment]
Ok, I'm baffled @sbenthall . I'm now getting an error from ruff-format, which is apparently unhappy with a coding style change I made-- I think I moved a comment or two. I can't get ruff to run on my computer, as it says that the notebook isn't a JSON file at all.

**Comment by alanlujan91** [comment]
I think this should pass now, is it ready to merge @mnwhite ?

**Comment by mnwhite** [comment]
It should be. Any guesses for getting ruff to work for me?

**Comment by alanlujan91** [comment]
first thing i did was merge all the changes in master branch
then update ruff 
then `ruff format .\examples\Gentle-Intro\Gentle-Intro-To-HARK.ipynb`

@MridulS is there a way to let ruff make and push the changes needed instead of not passing?

**Pull request merged**
