### PR TITLE
Fast pytest

### PR DESCRIPTION
**Pull request by alanlujan91**
Please ensure your pull request adheres to the following guidelines:

- [ ] Tests for new functionality/models or Tests to reproduce the bug-fix in code.
- [ ] Updated documentation of features that add new functionality.
- [ ] Update CHANGELOG.md with major/minor changes.

### CODE REVIEW

**Comment by alanlujan91** [comment]
attempt to make running checks and tests faster through github actions. Unfortunately the machine we get for testing only seems to have 2 cores at most, which makes the effect of this change limited.

**Comment by sbenthall** [comment]
@MridulS

**Review by MridulS — APPROVED** [review]
Looks good @alanlujan91, but it looks like the renovatebot configs have also slipped in this PR. Should they be removed?

**Comment by alanlujan91** [comment]
@MridulS oh yeah, I'll remove those. 

However, I think we should have a discussion about renovatebot or some other dependency manager. Seems pretty useful.

**Pull request merged**
