### PR TITLE
Fix simulation performance of AggShockMarkovConsumerType

### PR DESCRIPTION
**Pull request by mnwhite**
Implementation of DiscreteDistribution in AggShockMarkovConsumerType was incomplete/awkward, leading to extreme performance problems for simulation.  Now fixed.

Also removed references to timeFwd() in one of the examples, and maybe a couple other comment or whitespace tweaks that happened to be in my active changes.

### CODE REVIEW

**Comment by mnwhite** [comment]
This includes my other two recent PRs.  See those threads for other explanation.

**Comment by sbenthall** [comment]
By "other recent PRs" you mean #690  and #698  ?

**Comment by sbenthall** [comment]
There are some edits to `examples/ConsumptionSaving/example_ConsAggShockModel.py` and `examples/ConsumptionSaving/example_ConsIndShock.py`.

There are also `.ipynb` versions of these examples.

Ideally, the two are synced up. I'm a little confused at this point as to why they aren't. We've been using jupyter lab/jupytext to keep those working together.

**Comment by sbenthall** [comment]
If the performance issue has been fixed, could you also reenable the automated test?

**Comment by mnwhite** [comment]
I'll try to do that, yes.  But I don't think it was ever enabled?  Maybe it
was.

Yes, those are the PRs.  That's why there's random stuff like edits to
examples in this PR-- I pulled in MNWcleanup so I could run the relevant
example.

I don't know anything about the notebooks.  Are we supposed to generate
notebooks from py files, or vice versa?

**Comment by MridulS** [comment]
Those are supposed to be synced up using jupytext. (Install it using pip install jupytext if not already present)

To sync a paired notebook with a .py file ->

jupytext  --sync path_to_python_file.py

**Comment by sbenthall** [comment]
Let's put the jupytext thing into the contributor guidelines

**Comment by mnwhite** [comment]
We'll need to adjust the target for one AggShock test due to the change in the RNG.  This test doesn't fully solve, but instead "quits early", so the distribution of shocks matters for the "result".

**Comment by mnwhite** [comment]
Tests are now passing, will be ready to merge soon.

**Comment by mnwhite** [comment]
This is ready to be merged again.

**Pull request merged**
