### PR TITLE
Time varying unemployment probability and income

### PR DESCRIPTION
**Pull request by Mv77**
This PR allows `CondIndShock` and its derivatives to use age-varying unemployment probabilities and unemployment incomes.

This can be done passing lists as the arguments for `UnempPrb` and `ÌncUnemp`. 

- [x] Tests for new functionality/models or Tests to reproduce the bug-fix in code.
- [x] Updated documentation of features that add new functionality.
- [x] Update CHANGELOG.md with major/minor changes.

### CODE REVIEW

**Comment by Mv77** [comment]
Addresses https://github.com/econ-ark/HARK/issues/1015

**Comment by sbenthall** [comment]
Adding a variable name to a list called `time_varying` does not, in itself, make the code function in a way such that, say, a list of values is interpreted in all parts of the program as a time-varying parameter.

There are many open tickets that are about make a more unified and coherent approach to time-varying parameters. #95 #664 #890 #991 among others

**Comment by alanlujan91** [comment]
@llorracc I think that's correct. If we want a variable to be time-varying in some cases, even if it's in few cases and the main use case is time-fixed, the variable has to be added to `time_vary` and given as a list `[x]` of one element. Something we have been thinking about with the AgentPopulation in SHARKFin is how to flexibly infer time (and agent) variability depending on the argument passed.

**Review by alanlujan91 — APPROVED** [review]
Changes look good to me! 

A quick suggestion is that sometimes the types of parameters might be ints. I saw that you had to change this in some tests to make them floats. I assume this was for the type checks? 

Something that can help with type checks is `isinstance(x, (int, float))` to catch any scalar parameter.

**Comment by Mv77** [comment]
Great, this is ready to merge then.

Thank you all!

**Pull request merged**
