### PR TITLE
Update Demo.py

### PR DESCRIPTION
**Pull request by JohnYeabinMoon**
This is extremely helpful. Thank you guys. I corrected minor details. Please disregard if you intentionally used 'credit_change' in 'FirstDiffMPC_Income' function.

### CODE REVIEW

**Comment by dclow** [comment]
I actually did mean to use credit change there.  My intent was to change income by the same amount as we change credit, so that any differences between the two MPC approximations are (hopefully) due to actual differences in the theoretical MPCs, rather than in the quality of the approximation or anything.

I agree this is confusing though.  What if we changed 

# Declare how much we want to increase income by
income_change = .001

 to

# Declare how much we want to increase income by
# Change income by the same amount we change credit, so that the two MPC 
# approximations are comparable
income_change = credit_change 

?

**Comment by dclow** [comment]
Whoops, I put in hashtags for Python comments.  But github.com interpreted that as a Markdown command to make the font bold... so just imagine the bold words are Python comments

**Comment by JohnYeabinMoon** [comment]
It makes more sense to me!

**Comment by dclow** [comment]
I don't have write access to this PR so I can't make changes to it myself.

I've made the changes we agreed to and issued a new PR, so I'm closing this one

**Pull request closed without merging**
