### PR TITLE
Dynamic Interest Rate

### PR DESCRIPTION
**Pull request by alanlujan91**
This should close one of #1106 or #1132 or both. Should also address https://github.com/sbenthall/SHARKFin/issues/186#issuecomment-1410520453. 

- [x] Tests for new functionality/models or Tests to reproduce the bug-fix in code.
- [x] Updated documentation of features that add new functionality.
- [x] Update CHANGELOG.md with major/minor changes.

Can @wdu9 and @dedwar65 also review this?

With apologies to @dedwar65, this might affect #1219. (Going back to `agent.Rfree` without index in notebook). 

The logic is as follows:
If Rfree is an int, float: it is time invariant. 
If Rfree is a list of length 1: it is time invariant **and recast as a float**. 
If Rfree is a list of length n>1: it is time varying and should be same length as T_cycle. 
If Rfree is an array: it is time invariant (for Markov types)

Everywhere else where we want to use Rfree (as in calculations) we should first check the type then use appropriately (indexed if time varying).

### CODE REVIEW

**Comment by llorracc** [comment]
This seems like a sound temporary fix.

But this problem illustrates why my strongly held view is that the default way of building models should be to define a terminal period, then define the problem for $T-1$, then define the solution for $T-2$, and so on.  Part of the "defining" would be to specify the value for $R$ that is period-specific.

My way of doing things would get rid of a lot of extraneous baggage (like this).  

Wish we'd done it that way from the start.  (My fault that we didn't).

**Comment by dedwar65** [comment]
Hey Alan,

Just took a look at the PR. I think I understand what’s going on (w.r.t. the different cases for the time-varying interest rate).

Just to be clear though: does this mean I need to go back to the “ConsPortfolioModel” notebook and remove the subscript? The PR with that change still hasn’t been merged in yet, so I don’t think it should be much of a problem.

Let me know,
Decory

From: alanlujan91 ***@***.***>
Date: Wednesday, February 1, 2023 at 8:34 PM
To: econ-ark/HARK ***@***.***>
Cc: Decory Edwards ***@***.***>, Mention ***@***.***>
Subject: [econ-ark/HARK] Dynamic Interest Rate (PR #1221)

      External Email - Use Caution





This should close one of #1106<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fecon-ark%2FHARK%2Fissues%2F1106&data=05%7C01%7Cdedwar65%40jhu.edu%7Ccb1b0459915c4aa78b5d08db04bd996d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638108984598751282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fuLoDVfFM9yO0VOXE8rcTdvIlsZ%2F6pE5Le%2Fwn%2FmOMbw%3D&reserved=0> or #1132<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fecon-ark%2FHARK%2Fissues%2F1132&data=05%7C01%7Cdedwar65%40jhu.edu%7Ccb1b0459915c4aa78b5d08db04bd996d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638108984598751282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IrXIzMsVli924xB7PFKBHkpb8lmKPIRZ63doMFJO%2BiQ%3D&reserved=0> or both. Should also address sbenthall/SHARKFin#186 (comment)<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsbenthall%2FSHARKFin%2Fissues%2F186%23issuecomment-1410520453&data=05%7C01%7Cdedwar65%40jhu.edu%7Ccb1b0459915c4aa78b5d08db04bd996d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638108984598751282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qSPQoh371oU0e9KUQI04ivePpMkvNupciD7va61UBD4%3D&reserved=0>.

  *   Tests for new functionality/models or Tests to reproduce the bug-fix in code.
  *   Updated documentation of features that add new functionality.
  *   Update CHANGELOG.md with major/minor changes.

Can @wdu9<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwdu9&data=05%7C01%7Cdedwar65%40jhu.edu%7Ccb1b0459915c4aa78b5d08db04bd996d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638108984598907523%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HbcctO0sgUrA6D8oE98fpHD%2BXApyGSbt2Q2c%2BwFMVZQ%3D&reserved=0> and @dedwar65<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdedwar65&data=05%7C01%7Cdedwar65%40jhu.edu%7Ccb1b0459915c4aa78b5d08db04bd996d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638108984598907523%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JjblSvod%2FHFTZBPS79LW2JcOlkngiSyR%2FKnbHXvNwxA%3D&reserved=0> also review this?

With apologies to @dedwar65<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdedwar65&data=05%7C01%7Cdedwar65%40jhu.edu%7Ccb1b0459915c4aa78b5d08db04bd996d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638108984598907523%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JjblSvod%2FHFTZBPS79LW2JcOlkngiSyR%2FKnbHXvNwxA%3D&reserved=0>, this might affect #1219<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fecon-ark%2FHARK%2Fpull%2F1219&data=05%7C01%7Cdedwar65%40jhu.edu%7Ccb1b0459915c4aa78b5d08db04bd996d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638108984598907523%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RcxPX%2Fq7BDSVQODkKaWpdzCyz9Vu84QUEnFTPfThhJI%3D&reserved=0>. (Going back to agent.Rfree without index in notebook).

The logic is as follows:
If Rfree is an int, float: it is time invariant.
If Rfree is a list of length 1: it is time invariant and recast as a float.
If Rfree is a list of length n>1: it is time varying and should be same length as T_cycle.
If Rfree is an array: it is time invariant (for Markov types)

Everywhere else where we want to use Rfree (as in calculations) we should first check the type then use appropriately (indexed if time varying).

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/econ-ark/HARK/pull/1221<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fecon-ark%2FHARK%2Fpull%2F1221&data=05%7C01%7Cdedwar65%40jhu.edu%7Ccb1b0459915c4aa78b5d08db04bd996d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638108984598907523%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5aLDjBufpeIu6bTjAtDQ2Nbc0%2BSrvOcHNOzrBsO12CM%3D&reserved=0>

Commit Summary

  *   a6b6027<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fecon-ark%2FHARK%2Fpull%2F1221%2Fcommits%2Fa6b60278453fd02522e38229703f4d4607ee098e&data=05%7C01%7Cdedwar65%40jhu.edu%7Ccb1b0459915c4aa78b5d08db04bd996d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638108984598907523%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kJs2zfYFZBoV2DyZ0LWrsWrU8cW9%2Bq0WPal%2BXkHqUfw%3D&reserved=0> make update_Rfree more robust
  *   5a47ed0<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fecon-ark%2FHARK%2Fpull%2F1221%2Fcommits%2F5a47ed0f99424381a2e0b53b503300e318dfc366&data=05%7C01%7Cdedwar65%40jhu.edu%7Ccb1b0459915c4aa78b5d08db04bd996d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638108984598907523%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=z%2F%2Fc0m69fEqeUS8JoGe9%2FXXwTs9Hfx9faY6V0jlgv24%3D&reserved=0> update notebooks

File Changes

(5 files<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fecon-ark%2FHARK%2Fpull%2F1221%2Ffiles&data=05%7C01%7Cdedwar65%40jhu.edu%7Ccb1b0459915c4aa78b5d08db04bd996d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638108984598907523%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=C5ZI1neTBmiwWJjcJX%2BjoPnfAWA8XVuk%2BjedB9CWE%2Bw%3D&reserved=0>)

  *   M HARK/ConsumptionSaving/ConsIndShockModel.py<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fecon-ark%2FHARK%2Fpull%2F1221%2Ffiles%23diff-7f09d28a3d4136ae35d8835cd1352f060da6e0114fe617c34374c8b57d41a57e&data=05%7C01%7Cdedwar65%40jhu.edu%7Ccb1b0459915c4aa78b5d08db04bd996d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638108984598907523%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FPxMSbuaOqGFxBku4WAVMFsG7uRx7IcDGmbGo0doQs8%3D&reserved=0> (55)
  *   M HARK/ConsumptionSaving/ConsRiskyAssetModel.py<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fecon-ark%2FHARK%2Fpull%2F1221%2Ffiles%23diff-f073beba06b2b2768c998126f4b5a017cb220d60ec4380315af6f13dab0ecea3&data=05%7C01%7Cdedwar65%40jhu.edu%7Ccb1b0459915c4aa78b5d08db04bd996d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638108984598907523%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fVpL78hkZ%2BRkuj1FqOp5K%2FwfHk39LEUEDPmdzaJxXyg%3D&reserved=0> (22)
  *   M HARK/ConsumptionSaving/tests/test_ConsPortfolioFrameModel.py<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fecon-ark%2FHARK%2Fpull%2F1221%2Ffiles%23diff-6909a7798437228fda4bbf3a9250af3236148d029a23c0f89c37994e3aa4b324&data=05%7C01%7Cdedwar65%40jhu.edu%7Ccb1b0459915c4aa78b5d08db04bd996d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638108984598907523%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=C2WC6Gw0Uzgt2vLmySaizVj5cPyuTkkifHDqxJD%2BngA%3D&reserved=0> (5)
  *   M examples/ConsPortfolioModel/example_ConsPortfolioModel.ipynb<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fecon-ark%2FHARK%2Fpull%2F1221%2Ffiles%23diff-6feb2c247382948eddf34cec2e650999475281e974b4f501cc58de2db4fa4484&data=05%7C01%7Cdedwar65%40jhu.edu%7Ccb1b0459915c4aa78b5d08db04bd996d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638108984598907523%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qY357%2BbXht3pKfNWqKshy7%2FXrOnoLsgwaghvnwx1Q38%3D&reserved=0> (237)
  *   M examples/ConsPortfolioModel/example_ConsPortfolioModel.py<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fecon-ark%2FHARK%2Fpull%2F1221%2Ffiles%23diff-82d972a720bc462b7f7be0c28699678252c3ecae545af4dcae8f50ffc0d66cb0&data=05%7C01%7Cdedwar65%40jhu.edu%7Ccb1b0459915c4aa78b5d08db04bd996d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638108984598907523%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jBQvC%2B444LyVgy9XSdhXO6XJUIotYfnYVpy6exsZQtw%3D&reserved=0> (91)

Patch Links:

  *   https://github.com/econ-ark/HARK/pull/1221.patch<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fecon-ark%2FHARK%2Fpull%2F1221.patch&data=05%7C01%7Cdedwar65%40jhu.edu%7Ccb1b0459915c4aa78b5d08db04bd996d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638108984598907523%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=K5KC2qUmJUx28hSDHbB4oLFfv3DZU7HQ%2BzJNCGCk3oA%3D&reserved=0>
  *   https://github.com/econ-ark/HARK/pull/1221.diff<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fecon-ark%2FHARK%2Fpull%2F1221.diff&data=05%7C01%7Cdedwar65%40jhu.edu%7Ccb1b0459915c4aa78b5d08db04bd996d%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638108984598907523%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MgHorIHBXE2aHjOv%2B%2FkZy2wpsjLE2Eh4g9tyTXAZZbk%3D&reserved=0>

**Comment by alanlujan91** [comment]
@dedwar65 if this gets merged before yours, then the process should be to merge master back to your PR, then address any conflicts that come from that. Trying to preempt changes before they are on master might cause more issues. We can work on it together once it's needed.

**Comment by llorracc** [comment]
@alanlujan91, this is not marked "Ready-To-Merge" but my sense is that you think it is?

I guess we still don't have a workflow to test a PR against DemARKs; but if I merge it, can you trigger a retest of the DemARKs and reverse my merge if problems crop up?

**Comment by alanlujan91** [comment]
This is tagged as Ready to Merge. Not sure why you can't see it. But yes I can revert if needed.

**Comment by llorracc** [comment]
Oh, I see the Ready-To-Merge label now.  Didn't know where to look.

Merging ...

**Pull request merged**
