### PR TITLE
Add Methods to Compute Jacobian Matrices

### PR DESCRIPTION
**Pull request by wdu9**
Please ensure your pull request adheres to the following guidelines:

- [x] Tests for new functionality/models or Tests to reproduce the bug-fix in code.
- [x] Updated documentation of features that add new functionality.
- [x] Update CHANGELOG.md with major/minor changes.

### CODE REVIEW

**Comment by wdu9** [comment]
@Mv77 @AMonninger A   Could you guys take a look at this when you get the chance?

**Comment by AMonninger** [comment]
Looks good to me!
(I like the comments in the code, they make it easy to follow)

**Comment by wdu9** [comment]
> Looks good to me! (I like the comments in the code, they make it easy to follow)

Just updated the documentation to be clearer in the calc_jacobian function. In particular, the fake news algorithm is much clearer now.

**Comment by AMonninger** [comment]
Looks good to me!
Minor Comments:
- In ConsIndShockModel.py line 2676: "Jacobian Matrix ia TxT square Matrix" --> "ia" instead of "is a"
- In ConsIndShockModel.py line 2711:  Remove commented line

**Review by alanlujan91 — APPROVED** [review]

**Pull request merged**
