### PR TITLE
Update EstimationParameters.py

### PR DESCRIPTION
**Pull request by JohnYeabinMoon**

### CODE REVIEW

**Comment by mnwhite** [comment]
"beth" is correct.  See SolvingMicroDSOPs.pdf, which uses the Hebrew letter beth (or bet) as a multiplicative shifter for an age-varying sequence of discount factors.

**Comment by JohnYeabinMoon** [comment]
Oh yeah!

**Comment by mnwhite** [comment]
Yeabin: Can you do another commit reverting beta --> beth?  Then I can merge.

**Comment by JohnYeabinMoon** [comment]
Of course. Check it please.

**Pull request merged**
